services:
  # Base de Datos MySQL
  - type: pserv
    name: hydrosave-db
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.db
    
  # Backend API
  - type: web
    name: hydrosave-api
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_HOST
        fromService:
          name: hydrosave-db
          type: pserv
          property: host
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        generateValue: true
      - key: DB_NAME
        value: proyecto_agua
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        fromService:
          name: hydrosave-frontend
          type: web
          property: host
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
        
  # Frontend Angular
  - type: web
    name: hydrosave-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist/frontend/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html